name: Build and Test Frontend & Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]   # upgraded to Node 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend steps
      - name: Install frontend dependencies
        working-directory: ./fontend
        run: npm ci

      - name: Build frontend
        working-directory: ./fontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./fontend
        run: npm test --if-present

      # Backend steps
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm test --if-present
